stages:
  - prepare
  - build
  - test


install_deps:
  stage: prepare
  script:
    - apt update
    - apt install -y --no-install-recommends g++ libsdl2-dev make cmake ninja-build
  cache:
    key: apt-cache
    paths:
      - /var/cache/apt/archives/


build_project:
  stage: build
  script:
    - echo "Using the build pipeline"
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    paths:
      - build/ 
    expire_in: 1 day 
  dependencies:
    - install_deps 
  rules:
    - if: $CI_COMMIT_BRANCH  


load_rom:
  stage: test
  script:
    - echo "just testing rom loading"
    - wget -O test_opcode.ch8 https://raw.githubusercontent.com/corax89/chip8-test-rom/master/test_opcode.ch8
    - make run test_opcode.ch8
    - sleep 5
    - chip8_pid=$(ps aux | awk '/chip8/ {print $2; exit}')
    - kill $chip8_pid
  artifacts:
    paths:
      - test_opcode.ch8
    expire_in: 1 day
  dependencies:
    - build_project

